# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 16:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donationDate', models.DateField(auto_now_add=True)),
                ('deliveryType', models.BooleanField(choices=[('U', 'user'), ('V', 'volunteer')], default='U', max_length=1)),
                ('deliveryDate', models.DateField()),
            ],
            options={
                'ordering': ('deliveryDate',),
                'verbose_name_plural': 'Donations',
            },
        ),
        migrations.CreateModel(
            name='Med',
            fields=[
                ('barcode', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('medName', models.CharField(max_length=90)),
                ('postedDate', models.DateField(auto_now_add=True, null=True)),
                ('expirationDate', models.DateField(null=True)),
                ('boxes', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ('medName',),
            },
        ),
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needDate', models.DateField(auto_now_add=True)),
                ('needMedName', models.CharField(blank=True, default='', max_length=100)),
                ('substance', models.CharField(blank=True, default='', max_length=100)),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('needNotes', models.TextField(blank=True, default='', max_length=500)),
            ],
            options={
                'ordering': ('needDate',),
                'verbose_name_plural': 'Needs',
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('pharmacyPhone', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('pharmacyName', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('pharmacyAddress', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='', max_length=500)),
                ('website', models.URLField(blank=True, default='', max_length=250)),
                ('supervisor', models.CharField(max_length=50)),
                ('supervisorMail', models.EmailField(blank=True, default='', max_length=254)),
                ('userName', models.CharField(max_length=100)),
                ('passWord', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('pharmacyPhone',),
                'verbose_name_plural': 'Pharmacies',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('userPhone', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.EmailField(default='', max_length=100)),
                ('userName', models.CharField(max_length=50, unique=True)),
                ('birthDate', models.DateField(null=True)),
                ('userAddress', models.CharField(default='', max_length=100)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('userName',),
                'verbose_name_plural': 'UserProfiles',
            },
        ),
        migrations.AddField(
            model_name='need',
            name='needPhone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nPhone', to='givmed.Pharmacy'),
        ),
        migrations.AddField(
            model_name='med',
            name='medPhone',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='meds', to='givmed.UserProfile'),
        ),
        migrations.AddField(
            model_name='donation',
            name='donatedPhone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dPhone', to='givmed.Pharmacy'),
        ),
        migrations.AddField(
            model_name='donation',
            name='donationBarcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nBarcode', to='givmed.Med'),
        ),
        migrations.AddField(
            model_name='donation',
            name='donationId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dId', to='givmed.Need'),
        ),
        migrations.AddField(
            model_name='donation',
            name='donatorPhone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uPhone', to='givmed.UserProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='med',
            unique_together=set([('medPhone', 'barcode')]),
        ),
        migrations.AlterUniqueTogether(
            name='donation',
            unique_together=set([('donatorPhone', 'donatedPhone', 'donationBarcode', 'donationId')]),
        ),
    ]
