# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 22:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('givmed', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='donation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donatedPhone',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donationBarcode',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donationId',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donatorPhone',
        ),
        migrations.AlterUniqueTogether(
            name='med',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='med',
            name='medPhone',
        ),
        migrations.RemoveField(
            model_name='need',
            name='needPhone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.DeleteModel(
            name='Med',
        ),
        migrations.DeleteModel(
            name='Need',
        ),
        migrations.DeleteModel(
            name='Pharmacy',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
